# Generated by Django 5.0.6 on 2024-07-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_student_email_alter_student_note1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='note1',
            new_name='note_1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='note2',
            new_name='note_2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='note3',
            new_name='note_3',
        ),
    ]
